services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/pawa_hr
      - MYSQL_HOST=db
      - ALLOWED_HOSTS=["*"]
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://[IP_ADDRESS],http://localhost:3000}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hr_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    command: yarn dev
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hr_network


  db:
    image: mysql:8.0
    container_name: pawa_hr_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hr_network
  
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - hr_network

networks:
  hr_network:
    driver: bridge

volumes:
  mysql_data: