"""Add employee extra fields

Revision ID: 03e227e5191b
Revises: 0a5371b85ebc
Create Date: 2026-03-17 15:21:46.856686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e227e5191b'
down_revision: Union[str, Sequence[str], None] = '0a5371b85ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('airtime_allowance', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('termination_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'airtime_allowance')
    op.drop_column('employees', 'salary')
    # ### end Alembic commands ###
