"""update expenses and budget schemas

Revision ID: 7cbdf6114499
Revises: 03e227e5191b
Create Date: 2026-03-18 14:39:46.467200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbdf6114499'
down_revision: Union[str, Sequence[str], None] = '03e227e5191b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=False))
    # Update expense_type enum to include new values
    op.execute("ALTER TABLE expenses MODIFY COLUMN expense_type ENUM('TRANSPORTATION', 'ACCOMMODATION', 'SALARY', 'AIRTIME', 'RECRUITMENT', 'EMPLOYEE', 'TRAINING', 'SYSTEM', 'WELFARE', 'ENGAGEMENT', 'LEGAL') NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
